add nodeclass update job

diff --git a/.github/workflows/github-pipeline.yaml b/.github/workflows/github-pipeline.yaml
--- a/.github/workflows/github-pipeline.yaml
+++ b/.github/workflows/github-pipeline.yaml
@@ -90,9 +90,9 @@ jobs:
       #     ls -l ${{ env.WORK_DIR }}/state.config
 
       # Temporarily modify the .gitignore so that terraform allows it to not be ignored
-      - name: Allow Upload of .terraform/
-        run: |
-          echo "!.terraform/" >> .gitignore
+      # - name: Allow Upload of .terraform/
+      #   run: |
+      #     echo "!.terraform/" >> .gitignore
 
       - name: Initialize Terraform
         run: |
@@ -172,28 +172,67 @@ jobs:
           fi
 
 
-  # terraform-output:
-  #   name: "Process Terraform Outputs & Update NodeClass"
-  #   runs-on: ubuntu-latest
-  #   needs: terraform-apply
-  #   steps:
-  #     - name: Checkout Repository
-  #       uses: actions/checkout@v3
+  terraform-output:
+    name: "Process Terraform Outputs & Update NodeClass"
+    runs-on: ubuntu-latest
+    needs: terraform-apply
+    environment: LLM-EKS
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v3
 
-  #     - name: Update NodeClass with Terraform Outputs
-  #       run: |
-  #         # read Terraform output
-  #         cd $WORK_DIR
-  #         SUBNET_ID_1=$(terraform output -json private_subnet_ids | jq -r '.[0]')
-  #         SUBNET_ID_2=$(terraform output -json private_subnet_ids | jq -r '.[1]')
-  #         SECURITY_GROUP_ID=$(terraform output -raw eks_cluster_sg_id)
-  #         NODE_ROLE="${{ env.EKS_NODE_ROLE }}"
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.5.0
 
-  #         # replace NodeClass file's placeholders
-  #         sed -i "s#__SUBNET_ID_1__#$SUBNET_ID_1#g" ./eks/manifests/nodeclass.yaml
-  #         sed -i "s#__SUBNET_ID_2__#$SUBNET_ID_2#g" ./eks/manifests/nodeclass.yaml
-  #         sed -i "s#__SECURITY_GROUP_ID__#$SECURITY_GROUP_ID#g" ./eks/manifests/nodeclass.yaml
-  #         sed -i "s#__EKS_NODE_ROLE__#$NODE_ROLE#g" ./eks/manifests/nodeclass.yaml
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
+          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
+          aws-region: ${{ vars.REGION }}
 
-  #         echo "NodeClass updated successfully:"
-  #         cat ./eks/manifests/nodeclass.yaml
+      # download state.config file artifacts
+      - name: Restore Terraform State Config
+        uses: actions/download-artifact@v4
+        with:
+          name: state-config-artifacts
+          path: ${{ env.WORK_DIR }}
+
+      # ensure the config file is downloaded
+      - name: Debug Downloaded State Config
+        run: |
+          echo "Checking downloaded state.config file"
+          ls -l ${{ env.WORK_DIR }}/state.config || echo "File not found!"
+
+      - name: Initialize Terraform
+        run: |
+          cd ${{ env.WORK_DIR }}
+          terraform init -backend-config="./state.config"
+
+      - name: Update NodeClass with Terraform Outputs
+        run: |
+          # read Terraform output
+          cd ${{ env.WORK_DIR }}
+          SUBNET_ID_1=$(terraform output -json private_subnet_ids | jq -r '.[0]')
+          SUBNET_ID_2=$(terraform output -json private_subnet_ids | jq -r '.[1]')
+          SECURITY_GROUP_ID=$(terraform output -raw eks_cluster_sg_id)
+          NODE_ROLE="${{ env.EKS_NODE_ROLE }}"
+
+          # replace NodeClass file's placeholders
+          sed -i "s#__SUBNET_ID_1__#$SUBNET_ID_1#g" ./eks/manifests/nodeclass.yaml
+          sed -i "s#__SUBNET_ID_2__#$SUBNET_ID_2#g" ./eks/manifests/nodeclass.yaml
+          sed -i "s#__SECURITY_GROUP_ID__#$SECURITY_GROUP_ID#g" ./eks/manifests/nodeclass.yaml
+          sed -i "s#__EKS_NODE_ROLE__#$NODE_ROLE#g" ./eks/manifests/nodeclass.yaml
+
+          echo "NodeClass updated successfully:"
+          cat ./eks/manifests/nodeclass.yaml
+
+      
+      - name: Save Terraform Init Data and state config file for apply job
+        uses: actions/upload-artifact@v4
+        with:
+          name: nodeclass-artifacts
+          path: |
+            ${{ env.WORK_DIR }}/eks/manifests/nodeclass.yaml
